FRONTEND_DIR = frontend_admin
BACKEND_DIR = backend
STATIC_DIR = $(BACKEND_DIR)/ui/static
GO_MAIN = $(BACKEND_DIR)/cmd/main.go
BIN = blog_server

.PHONY: build-windows build-linux frontend-windows frontend-linux backend-windows backend-linux clean-windows clean-linux run-windows run-linux

# --- FRONTEND ---
frontend-windows:
	cd $(FRONTEND_DIR) && pnpm install && pnpm build
	powershell -Command "if (!(Test-Path $(STATIC_DIR))) { New-Item -ItemType Directory -Path $(STATIC_DIR) }"
	powershell -Command "Remove-Item -Recurse -Force $(STATIC_DIR)\*"
	powershell -Command "Copy-Item -Recurse -Force $(FRONTEND_DIR)\dist\* $(STATIC_DIR)"

frontend-linux:
	cd $(FRONTEND_DIR) && pnpm install && pnpm build
	rm -rf $(STATIC_DIR)/*
	cp -r $(FRONTEND_DIR)/dist/* $(STATIC_DIR)/

# --- BACKEND ---
backend-windows:
	cd $(BACKEND_DIR) && go build -ldflags="-s -w" -o $(BIN).exe ./cmd/main.go && powershell -Command "Copy-Item $(BIN).exe ..\\$(BIN).exe"

backend-linux:
	cd $(BACKEND_DIR) && go build -ldflags="-s -w" -o $(BIN) ./cmd/main.go && cp $(BIN) ../$(BIN)

# --- CLEAN ---
clean-windows:
	powershell -Command "if (Test-Path $(STATIC_DIR)) { Remove-Item -Recurse -Force $(STATIC_DIR)\* }"
	powershell -Command "if (Test-Path $(BIN).exe) { Remove-Item -Force $(BIN).exe }"

clean-linux:
	rm -rf $(STATIC_DIR)/*
	rm -f $(BIN)

# --- BUILD ---
build-windows: frontend-windows backend-windows

build-linux: frontend-linux backend-linux

# --- RUN ---
run-windows: build-windows
	./$(BIN).exe

run-linux: build-linux
	./$(BIN)
